# Generated by Django 3.2.4 on 2021-10-18 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordencompra.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0003_auto_20211018_1347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordencompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(ordencompra.models.OrderStatus['CREADO'], 'CREADO'), (ordencompra.models.OrderStatus['PAGADO'], 'PAGADO'), (ordencompra.models.OrderStatus['COMPLETADO'], 'COMPLETADO'), (ordencompra.models.OrderStatus['CANCELADO'], 'CANCELADO')], default=ordencompra.models.OrderStatus['CREADO'], max_length=50)),
                ('total_envio', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
