# Generated by Django 3.2.4 on 2021-10-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210822_1618'),
        ('carrito', '0002_carrito_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='Producto',
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
    ]
