# Generated by Django 3.2.4 on 2021-08-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210822_1618'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='producto',
            field=models.ManyToManyField(to='productos.Producto'),
        ),
    ]
